# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1147, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.reportLayout = QtWidgets.QVBoxLayout()
        self.reportLayout.setObjectName("reportLayout")
        self.report = QtWidgets.QTableWidget(self.centralwidget)
        self.report.setMinimumSize(QtCore.QSize(410, 0))
        self.report.setMaximumSize(QtCore.QSize(410, 16777215))
        self.report.setShowGrid(True)
        self.report.setGridStyle(QtCore.Qt.SolidLine)
        self.report.setRowCount(2)
        self.report.setObjectName("report")
        self.report.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.report.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.report.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.report.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.report.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.report.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.report.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.report.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.report.setItem(1, 1, item)
        self.report.horizontalHeader().setVisible(True)
        self.report.horizontalHeader().setDefaultSectionSize(204)
        self.report.horizontalHeader().setMinimumSectionSize(0)
        self.report.horizontalHeader().setStretchLastSection(False)
        self.report.verticalHeader().setVisible(False)
        self.report.verticalHeader().setCascadingSectionResizes(False)
        self.report.verticalHeader().setDefaultSectionSize(22)
        self.report.verticalHeader().setSortIndicatorShown(False)
        self.report.verticalHeader().setStretchLastSection(False)
        self.reportLayout.addWidget(self.report)
        self.gridLayout.addLayout(self.reportLayout, 0, 0, 1, 1)
        self.imageLayout = QtWidgets.QVBoxLayout()
        self.imageLayout.setObjectName("imageLayout")
        self.image = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("View/StartImage.jpg"))
        self.image.setScaledContents(False)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.imageLayout.addWidget(self.image)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.openImage = QtWidgets.QPushButton(self.centralwidget)
        self.openImage.setObjectName("openImage")
        self.buttonLayout.addWidget(self.openImage)
        self.recognizeImage = QtWidgets.QPushButton(self.centralwidget)
        self.recognizeImage.setObjectName("recognizeImage")
        self.buttonLayout.addWidget(self.recognizeImage)
        self.imageLayout.addLayout(self.buttonLayout)
        self.gridLayout.addLayout(self.imageLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1147, 18))
        self.menubar.setObjectName("menubar")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setObjectName("file")
        self.help = QtWidgets.QMenu(self.menubar)
        self.help.setObjectName("help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.open = QtWidgets.QAction(MainWindow)
        self.open.setObjectName("open")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.recognize = QtWidgets.QAction(MainWindow)
        self.recognize.setObjectName("recognize")
        self.exportToJson = QtWidgets.QAction(MainWindow)
        self.exportToJson.setObjectName("exportToJson")
        self.file.addAction(self.open)
        self.file.addAction(self.recognize)
        self.file.addAction(self.exportToJson)
        self.file.addSeparator()
        self.file.addAction(self.exit)
        self.help.addAction(self.about)
        self.menubar.addAction(self.file.menuAction())
        self.menubar.addAction(self.help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Установить метки"))
        self.report.setSortingEnabled(True)
        item = self.report.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.report.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.report.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Метка"))
        item = self.report.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Уверенность, %"))
        __sortingEnabled = self.report.isSortingEnabled()
        self.report.setSortingEnabled(False)
        item = self.report.item(0, 0)
        item.setText(_translate("MainWindow", "Dog"))
        item = self.report.item(0, 1)
        item.setText(_translate("MainWindow", "99"))
        item = self.report.item(1, 0)
        item.setText(_translate("MainWindow", "Cat"))
        item = self.report.item(1, 1)
        item.setText(_translate("MainWindow", "1"))
        self.report.setSortingEnabled(__sortingEnabled)
        self.openImage.setText(_translate("MainWindow", "Открыть изображение"))
        self.recognizeImage.setText(_translate("MainWindow", "Найти метки"))
        self.file.setTitle(_translate("MainWindow", "Файл"))
        self.help.setTitle(_translate("MainWindow", "Справка"))
        self.about.setText(_translate("MainWindow", "О программе"))
        self.open.setText(_translate("MainWindow", "Открыть изображение"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.recognize.setText(_translate("MainWindow", "Найти метки"))
        self.exportToJson.setText(_translate("MainWindow", "Экспорт в JSON"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
